### ISSUE TITLE
Color scheme of the website/template

### ISSUE THREAD

**Issue by ricardomar** [piazzai/jekyll-nagymaros#1]
Dear Michele Piazzai,

I want to extend my gratitude for sharing this template with such good documentation.

I'm curious if it's feasible (perhaps through a straightforward flag or label in the configurations) to adjust the color scheme of the entire website/template from gray to blue, red, or any other hue following the open color colormap.

best,
Ricardo Martins

**Comment by piazzai** [comment]
Hi Ricardo! Thanks for your interest in the theme. I had already planned to implement the feature you suggest, so I took the opportunity to finally do so. I released a new version of the theme (v2.0.0) where skin customization is possible. The procedure is documented in the README.

In short, it involves creating a `_data/skin.yml` file and setting a new value for any color you want to change. The README provides a full list of defaults that you can override. You will need to override several in order to come up with a coherent color scheme, so you should probably play around and see what works.

Please let me know if there is any problem or doubt.

**Comment by ricardomar** [comment]
thank you! :)
